INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (1, 10, 'Octane Gel', 17, 8);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (2, 100, 'Classmate Longbook', 17, 8);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (4, 500, 'Apple 15', 3, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (5, 550, 'Apple 15 Pro', 3, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (6, 600, 'Apple 15 Pro Max', 3, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (7, 300, 'Apple Airpods Max', 19, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (8, 150, 'Apple Airpods 2', 19, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (9, 200, 'Apple Airpods 3', 19, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (10, 250, 'Apple iPad mini', 20, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (11, 400, 'Apple iPad Pro', 20, 12);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (12, 500, 'Lenovo Ideapad 500', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (13, 600, 'Lenovo Legion 5', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (14, 600, 'Lenovo Legion 3', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (15, 700, 'Lenovo Slim 5i', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (16, 800, 'Lenovo Thinkpad 14', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (17, 850, 'Lenovo Thinkpad 15', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (18, 650, 'Lenovo Yoga 3', 4, 11);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (19, 350, 'Samsung Galaxy S24', 3, 5);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (20, 450, 'Samsung Galaxy S24 plus', 3, 5);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (21, 650, 'Samsung Galaxy S24 Ultra', 3, 5);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (22, 350, 'Sony HT-A5000', 18, 6);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (23, 450, 'Sony HT-A9000', 18, 6);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (24, 450, 'Samsung Q-990B', 18, 6);
INSERT INTO products (product_id, price, product_name, category_id, supplier_id) VALUES (25, 350, 'Samsung Q-990A', 18, 5);
