INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (1, 'value.elec@gmail.com', 'Value Electronics');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (2, 'shoes@gmail.com', 'Shoes Enterprises');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (4, 'gazon.inc@gmail.com', 'Gazon Inc');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (5, 'samsung.elec@gmail.com', 'Samsung Electronics');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (6, 'sony@gmail.com', 'Sony Inc');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (7, 'camlin@gmail.com', 'Camlin');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (8, 'classmate@gmail.com', 'Classmate');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (9, 'hp.inc@gmail.com', 'HP Inc.');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (10, 'dell.inc@gmail.com', 'Dell Inc.');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (11, 'lenovo.inc@gmail.com', 'Lenovo Inc.');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (12, 'apple.inc@gmail.com', 'Apple Inc.');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (13, 'google.inc@gmail.com', 'Google Inc.');
INSERT INTO suppliers (supplier_id, supplier_email, supplier_name) VALUES (14, 'nothing.elec@gmail.com', 'Nothing Electronics');
